### ISSUE TITLE
Exception in prediction 

### ISSUE THREAD

**Issue by marnaoty** [danhper/suplearn-clone-detection#6]
Hello,

I'm trying to us a trained model for prediction.

I use the following command:

suplearn-clone predict ../test.txt -c ../config.yml -m ../../models/final/model-00.h5 -b src/b/ --filenames-path asts/asts.txt --asts-path asts/asts.json -o output.json

But I get the following Error:
ERROR failed: setting an array element with a sequence.

**Comment by danhper** [comment]
Hey, could you pass the `--debug` option and paste the output with the stack trace please?
Thanks!

**Comment by marnaoty** [comment]
just to give more details:

the first few lines of test.txt contain:

10/1/1136010.java , 10/1/1417042.py
10/1/1136010.java , 10/1/1530247.py
10/1/1136010.java , 10/1/1555041.py
10/1/1136010.java , 10/1/1566525.py
10/1/1136010.java , 10/1/1582493.py

Using simple instrumentation, I found that the error source is
 preds = self.model.predict(input_data, batch_size=batch_size)

it calls predict_loop from keras engine.
the error is raised by this line:
batch_outs = f(ins_batch)

the reason behind the error message is that f is trying to obtain a numpy array from a list of uneven lists.

I can alter the debug option and print you the stack trace if that helps more.

**Comment by marnaoty** [comment]
> Hey, could you pass the `--debug` option and paste the output with the stack trace please?
> Thanks!

sure, I was writing the previous reply when I got this answer. 
I will do it

**Comment by marnaoty** [comment]
Here is the traceback:

Traceback (most recent call last):
  File "suplearn-clone", line 6, in <module>
    cli.run()
  File "/Users/mohammedelarnaoty/Downloads/suplearn-clone-detection-master/suplearn_clone_detection/cli.py", line 184, in run
    run_command(args)
  File "/Users/mohammedelarnaoty/Downloads/suplearn-clone-detection-master/suplearn_clone_detection/cli.py", line 157, in run_command
    commands.predict(vars(args))
  File "/Users/mohammedelarnaoty/Downloads/suplearn-clone-detection-master/suplearn_clone_detection/commands.py", line 67, in predict
    predictor.predict(files)
  File "/Users/mohammedelarnaoty/Downloads/suplearn-clone-detection-master/suplearn_clone_detection/predictor.py", line 26, in predict
    preds = self.model.predict(input_data, batch_size=batch_size)
  File "/Users/mohammedelarnaoty/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1170, in predict
    steps=steps)
  File "/Users/mohammedelarnaoty/anaconda3/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 299, in predict_loop
    batch_outs = f(ins_batch)
  File "/Users/mohammedelarnaoty/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/Users/mohammedelarnaoty/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2655, in _call
    dtype=tf.as_dtype(tensor.dtype).as_numpy_dtype))
  File "/Users/mohammedelarnaoty/anaconda3/lib/python3.6/site-packages/numpy/core/numeric.py", line 492, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.

**Comment by danhper** [comment]
I see. I think this comes from one of the current limitation.
Basically either you choose a maximum length for the vectors (for the linearized AST; vectors will be either padded or truncated) and then the learning or prediction can be done in batch, either you need to set the batch size to 1. To make sure this is actually the issue, maybe try to set the batch size to 1 and see if it works. The issue with batch size 1 is of course that it's super slow so for training I think I was setting the max vector size around 500 or so.

**Comment by marnaoty** [comment]
It worked. Thank you for your assistance
